<?php
declare(strict_types=1);

use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\BlockRenderer;
use Loki\Field\Config\Config;
use LokiCheckout\Buckaroo\Component\Afterpay\AfterpayViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\CssUtils\Util\CssClass;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var CssClass $css */
/** @var AfterpayViewModel $viewModel */
/** @var ViewModelFactory $viewModelFactory */
/** @var BlockRenderer $blockRenderer */
/** @var ViewModelFactory $viewModelFactory */
/** @var Config $config */

$config = $viewModelFactory->create(Config::class);
?>
<div class="<?= /* @noEscape */
$css('field required grid grid-cols-2 gap-4') ?>">
    <label
        for="<?= $escaper->escapeHtml($viewModel->getElementId() . '-customer-dob') ?>"
        class="<?= /* @noScape */ $css('inline-block mt-2 md:mt-0 mb-1.5 text-right required', 'label') ?>"
        required
    >
        <?= __('Date of Birth:') ?>
        <?php if ($config->useRequiredBlock()): ?>
            <?= /* @noEscape */ $blockRenderer->html($block, 'loki-field-components.utils.required'); ?>
        <?php endif; ?>
    </label>
    <div>
        <input
            id="<?= $escaper->escapeHtml($viewModel->getElementId() . '-customer-dob') ?>"
            class="<?= $css('form-input w-full disabled:bg-zinc-100', 'input') ?>"
            @change="saveCustomerDob"
            value="<?= $viewModel->getCustomerDob() ?>"
            type="date"
            required
        />
    </div>

    <label
        for="<?= $escaper->escapeHtml($viewModel->getElementId() . '-customer-iban') ?>"
        class="<?= /* @noScape */ $css('inline-block mt-2 md:mt-0 mb-1.5 text-right', 'label') ?>"
        required
    >
        <?= __('Bank Account Number:') ?>
        <?php if ($config->useRequiredBlock()): ?>
            <?= /* @noEscape */ $blockRenderer->html($block, 'loki-field-components.utils.required'); ?>
        <?php endif; ?>
    </label>
    <div>
        <input
            id="<?= $escaper->escapeHtml($viewModel->getElementId() . '-customer-iban') ?>"
            class="<?= $css('form-input w-full disabled:bg-zinc-100', 'input') ?>"
            @change="saveCustomerIban"
            value="<?= $viewModel->getCustomerIban() ?>"
            type="text"
            required
        />
    </div>

    <label
        for="<?= $escaper->escapeHtml($viewModel->getElementId() . '-terms-conditions') ?>"
        class="<?= /* @noScape */ $css('inline-block mt-2 md:mt-0 mb-1.5 text-right', 'label') ?>"
        required
    >
        <?= __('Terms and Conditions:') ?>
        <?php if ($config->useRequiredBlock()): ?>
            <?= /* @noEscape */ $blockRenderer->html($block, 'loki-field-components.utils.required'); ?>
        <?php endif; ?>
    </label>
    <div class="<?= /* @noScape */ $css('', 'terms-container') ?>">
        <input
            id="<?= $escaper->escapeHtml($viewModel->getElementId() . '-terms-conditions') ?>"
            class="<?= $css('form-input w-full disabled:bg-zinc-100', 'terms-input') ?>"
            @change="saveTermsCondition"
            <?php if ($viewModel->getTermsCondition() === 1): ?>checked<?php endif; ?>
            type="checkbox"
            required
        />

        <label
            for="<?= $escaper->escapeHtml($viewModel->getElementId() . '-terms-conditions') ?>"
            class="<?= /* @noScape */ $css('inline', 'terms-label') ?>"
            required
        >
            <?= __('The general Terms and Conditions for the Riverty payment method apply. The privacy policy of Riverty can be found here.') ?>
            <?php if ($config->useRequiredBlock()): ?>
                <?= /* @noEscape */ $blockRenderer->html($block, 'loki-field-components.utils.required'); ?>
            <?php endif; ?>
        </label>

        <div class="<?= /* @noScape */ $css('mt-4', 'terms-text') ?>">
            <?= __(
                $viewModel->getTermsConditionsText(),
                $viewModel->getPaymentMethodLabel(),
                $viewModel->getTermsAndConditionsUrl(),
                $viewModel->getPrivacyPolicyUrl(),
                $viewModel->getCookieStatementUrl(),
            ) ?>
        </div>
    </div>


</div>
