<?php
declare(strict_types=1);

/** @version 2.0.0 */

use Loki\Components\Factory\ViewModelFactory;
use LokiCheckout\Buckaroo\Component\Creditcard\CreditcardViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\CssUtils\Util\CssClass;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var CssClass $css */
/** @var CreditcardViewModel $viewModel */
/** @var ViewModelFactory $viewModelFactory */

$cards = $viewModel->getCards();
?>
<div class="<?= /* @noEscape */ $css('mt-4') ?>">
    <span class="<?= /* @noScape */ $css('', 'label') ?>">
        <?= __('Select a Credit Card or Debit Card:') ?>
    </span>
    <div>
        <?php foreach ($cards as $card): ?>
            <div class="<?= $css('flex gap-3 my-3', 'item') ?>">
                <div class="<?= $css('w-8', 'item-image') ?>">
                    <img src="<?= $card['img'] ?>""/>
                </div>
                <input
                    id="<?= $escaper->escapeHtml($viewModel->getElementId() . '-' . $card['code']) ?>"
                    class="<?= $css('', 'item-input') ?>"
                    @change="selectCard"
                    <?php if ($viewModel->getValue() === $card['code']): ?>checked<?php endif; ?>
                    type="radio"
                    required
                    name="<?= $card['code'] ?>"
                />
                <label
                    for="<?= $escaper->escapeHtml($viewModel->getElementId() . '-' . $card['code']) ?>"
                    class="<?= $css('', 'item-label') ?>"
                >
                    <?= $card['name'] ?>
                </label>
            </div>
        <?php endforeach; ?>
    </div>
</div>
