<?php
declare(strict_types=1);

use Loki\Components\Factory\ViewModelFactory;
use LokiCheckout\Buckaroo\Component\Creditcard\CreditcardViewModel;
use LokiCheckout\Buckaroo\Component\Paybybank\PaybybankViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\CssUtils\Util\CssClass;

/** @version 3.0.0 */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var CssClass $css */
/** @var PayByBankViewModel $viewModel */
/** @var ViewModelFactory $viewModelFactory */

$issuers = $viewModel->getIssuers();
?>
<div class="<?= $escaper->escapeHtml($css('my-8')) ?>" role="group">
    <span class="<?= $escaper->escapeHtml($css('', 'label')) ?>">
        <?= $escaper->escapeHtml(__('Select an issuer:')) ?>
    </span>
    <div>
        <?php foreach ($issuers as $card): ?>
            <div class="<?= $escaper->escapeHtml($css('flex gap-3 my-3', 'item')) ?>">
                <div class="<?= $escaper->escapeHtml($css('w-8', 'item-image')) ?>">
                    <img src="<?= $escaper->escapeUrl($card['img']) ?>" alt="<?= $escaper->escapeUrl($card['code']) ?>"/>
                </div>
                <input
                    id="<?= $escaper->escapeHtml($viewModel->getElementId() . '-' . $card['code']) ?>"
                    class="<?= $escaper->escapeHtml($css('', 'item-input')) ?>"
                    @change="selectIssuer"
                    <?php if ($viewModel->getValue() === $card['code']): ?>checked<?php endif; ?>
                    type="radio"
                    required
                    name="<?= $escaper->escapeHtml($card['code']) ?>"
                />
                <label
                    for="<?= $escaper->escapeHtml($viewModel->getElementId() . '-' . $card['code']) ?>"
                    class="<?= $escaper->escapeHtml($css('', 'item-label')) ?>"
                >
                    <?= $escaper->escapeHtml($card['name']) ?>
                </label>
            </div>
        <?php endforeach; ?>

        <?= /* @noEscape */ $blockRenderer->html($block,  'loki-components.utils.local-messages') ?>
    </div>
</div>
