<?php
declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */
/** @var CssClass $css */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 3.0.1 */
?>
<div class="<?= $escaper->escapeHtml($css('my-8')) ?>">
    <?= $escaper->escapeHtml(__('Please enter these fields as they appear on your bank account.')) ?>
</div>
