<?php
declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */
/** @var CssClass $css */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
?>
<div class="<?= /* @noEscape */ $css('my-4') ?>">
    <?= $escaper->escapeHtml(__('You will receive an email with further payment instructions when you place your order.')) ?>
</div>
