<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;
use LokiCheckout\Buckaroo\ViewModel\AdditionalPaymentDetails;

/** @version 2.0.3 */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var AdditionalPaymentDetails $additionalPaymentDetails */
$additionalPaymentDetails = $viewModelFactory->create(AdditionalPaymentDetails::class);
$details = $additionalPaymentDetails->getAdditionalDetails();

if (empty($details)) {
    return;
}
?>
<dl class="<?= $css('grid grid-cols-2', '@todo') ?>">
    <?php foreach ($details as $detailLabel => $detailValue): ?>
    <dt><?= /* @noEscape */ __($detailLabel) ?></dt>
    <dd><?= /* @noEscape */ $detailValue ?></dd>
    <?php endforeach; ?>
</dl>
