<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;
use LokiCheckout\Buckaroo\ViewModel\AdditionalPaymentDetails;

/** @version 2.0.13 */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var AdditionalPaymentDetails $additionalPaymentDetails */
/** @var CssClass $css */

$additionalPaymentDetails = $viewModelFactory->create(AdditionalPaymentDetails::class);
$details = $additionalPaymentDetails->getAdditionalDetails();

if (empty($details)) {
    return;
}
?>
<dl class="<?= $escaper->escapeHtml($css('grid grid-cols-2')) ?>">
    <?php foreach ($details as $detailLabel => $detailValue): ?>
    <dt><?= $escaper->escapeHtml(__($detailLabel)) ?></dt>
    <dd><?= /* @noEscape */ $detailValue ?></dd>
    <?php endforeach; ?>
</dl>
