<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 2.0.11 */
/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiCheckoutBuckarooAfterpay', () => ({
            ...LokiFieldComponentType,
            /*saveCustomerIban(event) {
                this.post({
                    customerIban: event.target.value,
                });
            },
            saveCustomerDob(event) {
                this.post({
                    customerDob: event.target.value,
                });
            },
            saveTermsCondition(event) {
                this.post({
                    termsCondition: event.target.checked ? 1 : 0,
                });
            }*/
        }));
    });
</script>
