<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 2.0.19 */
/** @var Template $block */
/** @var Escaper $escaper */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiCheckoutBuckarooCreditcard', () => ({
            ...LokiCheckoutPaymentMethodComponentType,
            requiredErrorMessage: '<?= $escaper->escapeHtml(__('Please enter a valid card')) ?>',
            selectCard(event) {
                const card = event.target.getAttribute('name');
                this.post(card);
            }
        }));
    });
</script>
