<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 3.0.2 */
/** @var Template $block */
/** @var Escaper $escaper */

?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiCheckoutBuckarooCreditcard', () => ({
            ...LokiCheckoutPaymentMethodComponentType,
            selectCard(event) {
                const card = event.target.getAttribute('name');
                this.post(card);
            }
        }));
    });
</script>
