<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 2.0.14 */
/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiCheckoutBuckarooCreditcard', () => ({
            ...LokiCheckoutComponentType,
            selectCard(event) {
                const card = event.target.getAttribute('name');
                this.post(card);
            }
        }));
    });
</script>
