<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 3.0.0 */
/** @var Template $block */
?>
<script>
    let buckarooHostedFieldsClient;

    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiCheckoutBuckarooHostedFields', () => ({
            ...LokiCheckoutComponentType,
            jwtToken: '',
            service: '',
            buckarooHostedFieldsClient: null,
            //tokenExpires: 0, @todo: Automatically expire token
            allowedIssuers: [],
            async initHostedFields() {
                var script = document.createElement('script');
                script.src = 'https://hostedfields-externalapi.prod-pci.buckaroo.io/v1/sdk';
                script.onload = () => {
                    this.renderHostedFields();
                };

                document.head.append(script);
            },
            async renderHostedFields() {
                const jwtToken = JSON.parse(JSON.stringify(this.jwtToken));
                const allowedIssuers = JSON.parse(JSON.stringify(this.allowedIssuers));

                this.buckarooHostedFieldsClient = new BuckarooHostedFieldsSdk.HFClient(jwtToken);
                this.buckarooHostedFieldsClient.setLanguage('nl'); // @todo
                this.buckarooHostedFieldsClient.setSupportedServices(allowedIssuers);

                await this.buckarooHostedFieldsClient.startSession((event) => {
                    this.buckarooHostedFieldsClient.handleValidation(
                        event,
                        this.elementId + '-cc-name-error',
                        this.elementId + '-cc-number-error',
                        this.elementId + '-cc-expiry-error',
                        this.elementId + '-cc-cvc-error'
                    );

                    this.valid = this.buckarooHostedFieldsClient.formIsValid();
                    this.service = this.buckarooHostedFieldsClient.getService();
                });

                const cardLogoStyling = {
                    height: "80%",
                    position: 'absolute',
                    border: '1px solid #d6d6d6',
                    borderRadius: "4px",
                    opacity: '1',
                    transition: 'all 0.3s ease',
                    right: '5px',
                    backgroundColor: 'inherit'
                };

                const styling = {
                    fontSize: "14px",
                    fontStyle: "normal",
                    fontWeight: 400,
                    fontFamily: 'Open Sans, Helvetica Neue, Helvetica, Arial, sans-serif',
                    textAlign: 'left',
                    background: '#fefefe',
                    color: '#333333',
                    placeholderColor: '#888888',
                    boxShadow: 'none',
                    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
                    cardLogoStyling: cardLogoStyling
                };

                const mountCardHolderNamePromise = this.buckarooHostedFieldsClient.mountCardHolderName("#" + this.elementId + "-cc-name-wrapper", {
                    id: "ccname",
                    placeHolder: "John Doe",
                    labelSelector: "#" + this.elementId + "-cc-name-label",
                    baseStyling: styling,
                }).then(field => {
                    field.focus();
                    return field;
                });

                const mountCardNumberPromise =  this.buckarooHostedFieldsClient.mountCardNumber("#" + this.elementId + "-cc-number-wrapper", {
                    id: "ccnumber",
                    placeHolder: "0000000000000000000",
                    labelSelector: "#" + this.elementId + "-cc-name-label",
                    baseStyling: styling,
                });

                const mountCardExpiryPromise =  this.buckarooHostedFieldsClient.mountExpiryDate("#" + this.elementId + "-cc-expiry-wrapper", {
                    id: "ccexpiry",
                    placeHolder: "01/30",
                    labelSelector: "#" + this.elementId + "-cc-name-label",
                    baseStyling: styling,
                });

                const mountCardCvcPromise =  this.buckarooHostedFieldsClient.mountCvc("#" + this.elementId + "-cc-cvc-wrapper", {
                    id: "cvc",
                    placeHolder: "000",
                    labelSelector: "#" + this.elementId + "-cc-name-label",
                    baseStyling: styling,
                });

                await Promise.all([
                    mountCardHolderNamePromise,
                    mountCardNumberPromise,
                    mountCardExpiryPromise,
                    mountCardCvcPromise,
                ]);
            },
            async beforePostNextStep() {
                if (false === this.buckarooHostedFieldsClient.formIsValid()) {
                    this.valid = false;
                    return;
                }

                // @todo: Add token expiration
                /*if (Date.now() > this.tokenExpiresAt) {
                    this.valid = false;
                    return;
                }*/

                this.valid = true;
                const paymentToken = await this.buckarooHostedFieldsClient.submitSession();
                this.post({
                    token: paymentToken,
                    service: this.service,
                });
            }
        }));
    });
</script>
